services:
  pyspark:
    image: jupyter/pyspark-notebook:x86_64-spark-3.5.0
    container_name: pyspark_workspace
    ports:
      - "8888:8888"          # JupyterLab
      - "4040-4045:4040-4045" # Spark UI
    volumes:
      # Lab 1 volumes
      - ./lab1/notebooks:/home/jovyan/lab1/work
      - ./lab1/data:/home/jovyan/lab1/data
      - ./lab1/streaming_input:/home/jovyan/lab1/streaming_input
      # Lab 2 volumes
      - ./lab2/notebooks:/home/jovyan/lab2/work
      - ./lab2/data:/home/jovyan/lab2/data
      - ./lab2/streaming_input:/home/jovyan/lab2/streaming_input
      - ./lab2/output:/home/jovyan/lab2/output
      - ./lab2/checkpoints:/home/jovyan/lab2/checkpoints
      - ./lab2/warehouse:/home/jovyan/lab2/warehouse
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - GRANT_SUDO=yes
    command: start-notebook.sh --NotebookApp.token=''
    networks:
      - data_network
    depends_on:
      - kafka1
      - kafka2
      - kafka3

  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.2
    container_name: zookeeper
    hostname: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    volumes:
      - zookeeper_data:/var/lib/zookeeper/data
      - zookeeper_log:/var/lib/zookeeper/log
    networks:
      - data_network

  kafka1:
    image: confluentinc/cp-kafka:7.3.2
    container_name: kafka1
    hostname: kafka1
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:19092,EXTERNAL://0.0.0.0:9092,HOST://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka1:19092,EXTERNAL://localhost:9092,HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_MIN_INSYNC_REPLICAS: 2
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_BROKER_RACK: "rack1"
    volumes:
      - kafka1_data:/var/lib/kafka/data
    depends_on:
      - zookeeper
    networks:
      - data_network

  kafka2:
    image: confluentinc/cp-kafka:7.3.2
    container_name: kafka2
    hostname: kafka2
    ports:
      - "9093:9093"
      - "29093:29093"
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:19093,EXTERNAL://0.0.0.0:9093,HOST://0.0.0.0:29093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka2:19093,EXTERNAL://localhost:9093,HOST://localhost:29093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_MIN_INSYNC_REPLICAS: 2
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_BROKER_RACK: "rack2"
    volumes:
      - kafka2_data:/var/lib/kafka/data
    depends_on:
      - zookeeper
    networks:
      - data_network

  kafka3:
    image: confluentinc/cp-kafka:7.3.2
    container_name: kafka3
    hostname: kafka3
    ports:
      - "9094:9094"
      - "29094:29094"
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:19094,EXTERNAL://0.0.0.0:9094,HOST://0.0.0.0:29094
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka3:19094,EXTERNAL://localhost:9094,HOST://localhost:29094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_MIN_INSYNC_REPLICAS: 2
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_BROKER_RACK: "rack3"
    volumes:
      - kafka3_data:/var/lib/kafka/data
    depends_on:
      - zookeeper
    networks:
      - data_network

  kafka-ui:
    image: ghcr.io/kafbat/kafka-ui:latest
    container_name: kafka-ui
    hostname: kafka-ui
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: kafka
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka1:19092,kafka2:19093,kafka3:19094
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
    depends_on:
      - kafka1
      - kafka2
      - kafka3
    networks:
      - data_network

volumes:
  kafka1_data:
  kafka2_data:
  kafka3_data:
  zookeeper_data:
  zookeeper_log:

networks:
  data_network:
    driver: bridge